# Generated by Django 2.0.2 on 2018-02-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='phones.PhoneNumber'),
        ),
    ]
