# Generated by Django 2.0.3 on 2018-03-09 16:46

from django.db import migrations, models
import phones.models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_phonenumber_sms_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='code',
            field=models.CharField(default=phones.models.generate_code, editable=False, max_length=8),
        ),
    ]
