# Generated by Django 2.0.3 on 2018-03-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0018_vote_created'),
        ('phones', '0004_auto_20180309_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='bypass_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='voter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='votes.VoterListItem'),
        ),
    ]
