# Generated by Django 2.0.3 on 2018-09-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20180312_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'numéro de téléphone', 'verbose_name_plural': 'numéros de téléphone'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'SMS', 'verbose_name_plural': 'SMS'},
        ),
    ]
