# Generated by Django 2.0.2 on 2018-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('B', 'Blanc')], max_length=1)),
            ],
        ),
    ]
