# Generated by Django 2.0.2 on 2018-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20180221_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('G', 'List générale'), ('E', 'Liste complémentaire européennes'), ('M', 'Liste complémentaire munucipales')], max_length=1, verbose_name='Type de liste')),
                ('departement', models.CharField(max_length=2, verbose_name='Code INSEE département')),
                ('commune', models.CharField(max_length=5, verbose_name='Code INSEE commune')),
                ('civilite', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'Mme')], max_length=1, verbose_name='Civilité')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom de naissance')),
                ('use_last_name', models.CharField(blank=True, max_length=255, verbose_name="Nom d'usage")),
                ('first_names', models.CharField(max_length=255, verbose_name='Prénoms')),
                ('birth_date', models.DateField(blank=True, verbose_name='Date de naissance')),
                ('birth_city_name', models.CharField(blank=True, max_length=255, verbose_name='Ville de naissance')),
                ('birth_departement_name', models.CharField(blank=True, max_length=255, verbose_name='Département de naissance')),
                ('birth_country_name', models.CharField(blank=True, max_length=255, verbose_name='Pays de naissance')),
                ('nationality', models.CharField(blank=True, max_length=255, verbose_name='Nationalité')),
                ('address1', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse 1")),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse 2")),
                ('street_number', models.CharField(blank=True, max_length=10, verbose_name='Numéro de voie')),
                ('street_type', models.CharField(blank=True, max_length=255, verbose_name='Type de voie')),
                ('street_label', models.CharField(blank=True, max_length=255, verbose_name='Nom de la voie')),
                ('place_name', models.CharField(blank=True, max_length=255, verbose_name='Lieu-dit')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='Code postal')),
                ('local_city_name', models.CharField(blank=True, max_length=255, verbose_name='Ville ou localité')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Pays')),
            ],
        ),
    ]
