# Generated by Django 2.0.2 on 2018-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_voterlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlistitem',
            name='file_line',
            field=models.IntegerField(default=0, verbose_name="Numéro de la ligne dans le fichier d'origine"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voterlistitem',
            name='origin_file',
            field=models.IntegerField(default=0, verbose_name="Identifiant du fichier d'origine"),
            preserve_default=False,
        ),
    ]
