# Generated by Django 2.0.2 on 2018-02-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20180222_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='voterlistitem',
            name='civilite',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'MME')], max_length=1, verbose_name='Civilité'),
        ),
    ]
