# Generated by Django 2.0.2 on 2018-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20180222_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Numéro de voie'),
        ),
    ]
