# Generated by Django 2.0.2 on 2018-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20180222_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
    ]
