# Generated by Django 2.0.2 on 2018-02-26 18:32
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_trigram_extension'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RunSQL(
            "CREATE INDEX index_list_full_name ON votes_voterlistitem "
            "USING gin(departement, (first_names|| ' ' || use_last_name || ' ' || last_name) gin_trgm_ops)",
            reverse_sql='drop index index_list_full_name;'
        )
    ]
