# Generated by Django 2.0.2 on 2018-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_voterlistitem_has_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='list_type',
            field=models.CharField(choices=[('G', 'Liste générale'), ('E', 'Liste complémentaire européennes'), ('M', 'Liste complémentaire municipales')], max_length=1, verbose_name='Type de liste'),
        ),
    ]
