# Generated by Django 2.0.2 on 2018-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20180305_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlistitem',
            name='has_voted',
        ),
        migrations.AddField(
            model_name='voterlistitem',
            name='vote_status',
            field=models.CharField(choices=[('N', 'Pas voté'), ('O', 'Vote en ligne'), ('P', 'Vote physique')], default='N', max_length=1, verbose_name='Statut du vote'),
        ),
    ]
