# Generated by Django 2.0.3 on 2018-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_voterlistitem_vote_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='with_list',
            field=models.BooleanField(default=False, editable=False),
            preserve_default=False,
        ),
    ]
