# Generated by Django 2.0.3 on 2018-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_vote_with_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Code postal'),
        ),
    ]
