# Generated by Django 2.0.3 on 2018-03-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_auto_20180309_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlistitem',
            name='departement',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Code INSEE département'),
        ),
    ]
