# Generated by Django 2.0.3 on 2018-03-10 10:58

from django.db import migrations, models
import votes.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_auto_20180310_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default=votes.models.generate_vote_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
