# Generated by Django 2.0.3 on 2018-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0018_vote_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEVoterListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email donnée au consulat')),
                ('first_names', models.CharField(max_length=255, verbose_name='Prénoms')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('has_voted', models.BooleanField(default=False, verbose_name='Statut du vote')),
            ],
        ),
    ]
