# Generated by Django 2.0.3 on 2018-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0019_fevoterlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fevoterlistitem',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email donnée au consulat'),
        ),
    ]
