# Generated by Django 2.0.3 on 2018-03-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20180312_1834'),
        ('votes', '0020_auto_20180313_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse email')),
                ('raw_number', models.CharField(max_length=40, verbose_name='Numéro (brut)')),
                ('requester', models.CharField(max_length=255, verbose_name='Demandeur')),
                ('declared_voter', models.CharField(max_length=255, verbose_name='Votant déclaré')),
                ('status', models.CharField(choices=[('re', 'À vérifier'), ('ok', 'Acceptée'), ('ko', 'Refusée'), ('du', 'Numéro déjà débloqué une fois'), ('in', "Le numéro transmis n'est pas un numéro valide"), ('un', "Le numéro n'a pas encore été utilisé"), ('ul', "Le numéro a été utilisé par quelqu'un de non-inscrit")], max_length=2, verbose_name='Statut de la demande')),
                ('answer_sent', models.BooleanField(default=False, editable=False, verbose_name='Message parti ?')),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.PhoneNumber')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='votes.VoterListItem')),
            ],
        ),
        migrations.AlterField(
            model_name='fevoterlistitem',
            name='has_voted',
            field=models.BooleanField(default=False, editable=False, verbose_name='Déjà voté'),
        ),
    ]
