# Generated by Django 2.0.3 on 2018-09-24 12:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0022_auto_20180316_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fevoterlistitem',
            options={'verbose_name': "électeur Français de l'étranger", 'verbose_name_plural': "électeurs Français de l'étranger"},
        ),
        migrations.AlterModelOptions(
            name='unlockingrequest',
            options={'verbose_name': "demande de déblocage d'un numéro de téléphone", 'verbose_name_plural': 'demandes de déblocages de numéros de téléphone'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote exprimé', 'verbose_name_plural': 'Votes exprimés'},
        ),
        migrations.AlterModelOptions(
            name='voterlistitem',
            options={'verbose_name': 'électeur inscrit', 'verbose_name_plural': 'électeurs inscrits'},
        ),
        migrations.AlterField(
            model_name='unlockingrequest',
            name='status',
            field=models.CharField(blank=None, choices=[('re', 'À vérifier'), ('ok', 'Acceptée'), ('ko', 'Refusée'), ('du', 'Numéro déjà débloqué une fois'), ('in', "Le numéro transmis n'est pas un numéro valide"), ('un', "Le numéro n'a pas encore été utilisé"), ('ul', "Le numéro a été utilisé par quelqu'un de non-inscrit"), ('ig', 'Demande à ignore (pas de réponse)')], default='re', max_length=2, verbose_name='Statut de la demande'),
        ),
        migrations.AddField(
            model_name='voterinformation',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.VoterListItem'),
        ),
    ]
