# Generated by Django 2.0.3 on 2018-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0023_auto_20180924_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinformation',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votes.VoterListItem'),
        ),
    ]
