# Generated by Django 2.0.3 on 2018-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistantMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=20)),
                ('text', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
