# Generated by Django 2.0.3 on 2018-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistantmessage',
            name='url_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
