# Generated by Django 2.0.3 on 2018-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0002_persistantmessage_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persistantmessage',
            options={'verbose_name': 'annonce'},
        ),
        migrations.AlterField(
            model_name='persistantmessage',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Info'), (25, 'Success'), (30, 'Warning'), (40, 'Error')], default=20),
        ),
    ]
