# Generated by Django 2.0.2 on 2018-03-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0003_auto_20180305_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bureau',
            old_name='lieu',
            new_name='place',
        ),
    ]
