# Generated by Django 2.0.2 on 2018-03-06 15:09

import bureaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0004_auto_20180306_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='assistant_code',
            field=models.CharField(default=bureaux.models.new_assistant_code, max_length=10, verbose_name="Code d'accès pour les assistant⋅e⋅s"),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Heure de d'ouverture du bureau"),
        ),
    ]
