# Generated by Django 2.0.3 on 2018-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0006_bureau_results_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='result2_blank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bulletins oranges : blancs'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='result2_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bulletins oranges : non'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='result2_null',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bulletins oranges : nuls'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='result2_yes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bulletins oranges : oui'),
        ),
    ]
