# Generated by Django 2.0.3 on 2018-03-09 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0007_auto_20180309_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureauoperator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'import"),
            preserve_default=False,
        ),
    ]
