# Generated by Django 2.0.3 on 2018-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0009_auto_20180309_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'Bureau de vote', 'verbose_name_plural': 'Bureaux de vote'},
        ),
    ]
