# Generated by Django 2.0.3 on 2018-09-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0011_auto_20180311_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'bureau de vote', 'verbose_name_plural': 'bureaux de vote'},
        ),
        migrations.AlterModelOptions(
            name='bureauoperator',
            options={'verbose_name': 'opérateur de bureaux de vote', 'verbose_name_plural': 'opérateurs de bureaux de votes'},
        ),
        migrations.AlterModelOptions(
            name='loginlink',
            options={'verbose_name': 'lien de connexion', 'verbose_name_plural': 'liens de connexions'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'opération sur un bureau', 'verbose_name_plural': 'opérations sur les bureaux'},
        ),
        migrations.AlterField(
            model_name='bureau',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='bureaux.BureauOperator', verbose_name='opérateur du bureau'),
        ),
    ]
