# Generated by Django 2.1.2 on 2018-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0013_auto_20181025_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureauoperator',
            options={'verbose_name': 'président⋅e de bureaux de vote', 'verbose_name_plural': 'président⋅e⋅s de bureaux de votes'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('OPERATOR_LOGIN', "Connexion d'un⋅e président⋅e"), ('START_BUREAU', 'Ouverture de bureau'), ('END_BUREAU', 'Fermeture de bureau'), ('SEND_RESULTS', 'Envoi des résultats'), ('ASSISTANT_LOGIN', "Connexion d'un⋅e assistant⋅e"), ('PERSON_VOTE', "Validation du vote d'un⋅e personne inscrite sur les listes")], editable=False, max_length=255, verbose_name="Type d'opération"),
        ),
    ]
