# Generated by Django 2.1.2 on 2018-10-30 15:11

import bureaux.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureaux', '0014_auto_20181030_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='assistant_code',
            field=models.CharField(default=bureaux.models.new_assistant_code, max_length=10, verbose_name="Code d'accès pour les assesseur⋅e⋅s"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('OPERATOR_LOGIN', "Connexion d'un⋅e opérateur⋅rice"), ('START_BUREAU', 'Ouverture de bureau'), ('END_BUREAU', 'Fermeture de bureau'), ('SEND_RESULTS', 'Envoi des résultats'), ('ASSISTANT_LOGIN', "Connexion d'un⋅e assesseur⋅e"), ('PERSON_VOTE', "Validation du vote d'un⋅e personne inscrite sur les listes")], editable=False, max_length=255, verbose_name="Type d'opération"),
        ),
    ]
